### ISSUE TITLE
Parse parameter issue

### ISSUE THREAD

**Issue by lsalamon** [David-Barrett-MS/ExchangePowerShellAutomationSample#4]
At source FormMain.cs routine ParseCommand has an wrong test.
Line "while ((i > 0) && (i < parameters.Length))"
change to:
"while ((i >= 0) && (i < parameters.Length))"

Try with this line command:
"Set-User -Identity userIdentity -Title \"Key One\""

**Comment by David-Barrett-MS** [comment]
Thanks.  I've changed this in the source but it won't be published for a while as I'm also implementing some missing features (such as certificate auth).

**Comment by lsalamon** [comment]
I made other tweaks to allow me to expand the number of powershell script formats that can be used:
        private static PSCommand ParseCommand(string commandLine)
        {
            PSCommand command = new PSCommand();
            int i = commandLine.IndexOf(" ");
            if (i < 0)
            {
                // The command has no parameters, so add as is
                command.AddCommand(commandLine);
                return command;
            }

            // Add the command, then we need to deal with parameters

            command.AddCommand(commandLine.Substring(0, i));
            string parameters = commandLine.Substring(i + 1);

            i = parameters.IndexOf("-");
            if (i < 0)
            {
                // We have parameters, but they are not named - we just add them to the command
                command.AddArgument(parameters);
                return command;
            }

            // Now parse and add parameters
            while ((i >= 0) && (i < parameters.Length))
            {
                int j = parameters.IndexOf("-", i + 1);
                if (j > 0)
                {
                    if (parameters[j - 1] != ' ')
                    {
                        j = parameters.IndexOf("-", j + 1);
                    }
                }
                if (j < 0) j = parameters.Length;
                int p = parameters.IndexOf(" ", i + 1);
                string sParamName = parameters.Substring(i + 1, p - i - 1);
                string sParamValue = parameters.Substring(p + 1, j - p - 1).Trim();
                if (sParamValue.StartsWith("\"") && sParamValue.EndsWith("\""))
                    sParamValue = sParamValue.Substring(1, sParamValue.Length - 2);
                if (string.Equals(sParamValue, "false"))
                {
                    command.AddParameter(sParamName, false);
                }
                else if (string.Equals(sParamValue, "true"))
                {
                    command.AddParameter(sParamName, true);
                }
                else
                {
                    if (sParamValue.StartsWith("@"))
                    {
                        sParamValue = sParamValue.Substring(2);
                        sParamValue = sParamValue.Substring(0, sParamValue.Length - 2);

                        int jj = sParamValue.IndexOf("=");

                        string operatio = sParamValue.Substring(0, jj);

                        sParamValue = sParamValue.Substring(jj + 2, sParamValue.Length - operatio.Length - 2);

                        var addresses = new Hashtable();
                        addresses.Add(operatio, sParamValue);

                        command.AddParameter(sParamName, addresses);
                    }
                    else
                    {
                        command.AddParameter(sParamName, sParamValue);
                    }
                }
                i = j;
            }

**Comment by David-Barrett-MS** [comment]
I've implemented some of the logic shared, though not the hashtable type.  It's beyond the scope of this sample, and if I start adding further types I'll never stop!  There may be a better way to parse the parameters, so I may return to this at some point.

Closing this issue as the bugs identified are now resolved.
